language: python
python:
	- "3.6"

install:
	- pip install -r requirements.txt

script:
	- export FILES="$(git diff --name-only $TRAVIS_COMMIT_RANGE)"
	- python3 src/models/resnet/cifar.py --lr 0.01 --resume True
